### ISSUE TITLE
Support s.bitstruct_wire //= s.bits_wire

### ISSUE THREAD

**Issue by jsn1993** [pymtl/pymtl3#195]
Yanghui Ou:

It seems that I cannot connect a bits interface  to a bitstruct interface nor does `s.bitstruct_wire //= s.bits_wire` seem to work.

`s.bitstruct_wire @= s.bits_wire` works. We may want to make it consistent?

**Comment by ptpan** [comment]
This now works with the `connect_bits2bitstruct` free function. A unit test under stdlib/connects verifies this:

https://github.com/pymtl/pymtl3/blob/4b3bc183b14ffacd069f48dc5997b00045aea53f/pymtl3/stdlib/connects/test/connect_bits2bitstruct_test.py#L147C42-L147C42
