### ISSUE TITLE
Failed to compile Verilator 4.224

### ISSUE THREAD

**Issue by metoofan** [pymtl/pymtl3#229]
I am on a MacBook Pro (High Sierra 10.13.6) and have downloaded Verilator 4.224 source code.
However, upon issuing "make" command, I do get the following error message:
Undefined symbols for architecture x86_64:
  "sc_time_stamp()", referenced from:
      vl_time_stamp64() in Vt_a1_first_cc__main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Vt_a1_first_cc] Error 1

I am not a software engineer, so I do appreciate if someone could clearly provide a detailed step by step resolution (if any) to me to remove the above error message.

**Comment by cbatten** [comment]
Hmmm .. we have been using Verilator 0.036 and haven't really tried using a newer version of Verilator recently. But regardless this seems like a Verilator question so your best bet is probably to ask on the Verilator mailing list? Does your MacBook Pro use an Intel processor or one of the newer ARM processors (i.e., Apple M1 or M2 silicon)? Google around I found this:

- https://github.com/verilator/verilator/issues/3283
