### ISSUE TITLE
README Verilator sentences

### ISSUE THREAD

**Issue by yihuajack** [pymtl/pymtl3#238]
In README.md, it writes:
> You can install Verilator using the standard package manager but the version available in the package repositories is several years old. This means you will need to build and install Verilator from source

However, the Verilator in APT package repos are very new:
> Verilator 4.038 2020-07-11 rev v4.036-114-g0cd4a57ad

Since to use package repos is better than building from source, is it better to instruct users to use package repos?

**Comment by cbatten** [comment]
Yep - but PyMTL3 doesn't work with 4.038 which is why we had to pin it to 4.036 ... we are actively working on getting it to work with the most recent version, but I do not know if those changes will make it work with 4.038 ... so you still might need to build it from source.
