### ISSUE TITLE
StreamSourceFL, StreamSinkFL missing.

### ISSUE THREAD

**Issue by hmohajeri** [pymtl/pymtl3#239]
from pymtl3.stdlib.stream import StreamSourceFL, StreamSinkFL

I can not find StreamSourceFL and StreamSinkFL in the directory and seems to be missing.

**Comment by cbatten** [comment]
That are in the ece4750-2022 branch

**Comment by hmohajeri** [comment]
Many thanks for quick response. Just one more question, is there any reason these files are not in the main branch? 

regards,

**Comment by ptpan** [comment]
We plan to merge the ece4750 course branch to the main branch very soon… sorry for the hassle!

**Comment by hmohajeri** [comment]
Thanks and happy new year.
