### ISSUE TITLE
Support multiple clock domains

### ISSUE THREAD

**Issue by mithro** [pymtl/pymtl3#74]
Apparently PyMTL doesn't support multiple clock domains? Supporting multiple clock domains is really essential. It is the only way to get high speed designs into FPGA devices.

**Comment by jsn1993** [comment]
Hmm multi clock domain is definitely on the roadmap. Part of the reason we currently don't support multiple clock domains is that we don't have much experience with it. I personally don't know how exactly multiple clock domains work ...
